// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetGameEventsData, PostGameRequestsData } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getGameEvents = <ThrowOnError extends boolean = false>(options?: Options<GetGameEventsData, ThrowOnError>) => (options?.client ?? client).get<unknown, unknown, ThrowOnError>({ url: '/game/events', ...options });

export const postGameRequests = <ThrowOnError extends boolean = false>(options: Options<PostGameRequestsData, ThrowOnError>) => (options.client ?? client).post<unknown, unknown, ThrowOnError>({
    url: '/game/requests',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
