// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

/**
 * FlopCard
 */
export type FlopCard = {
    type: string;
} | {
    type: string;
    add: number;
} | {
    type: string;
    value: number;
} | {
    type: string;
    multiplier: number;
} | {
    type: string;
};

/**
 * RoundPlayerSnapshot
 */
export type RoundPlayerSnapshot = {
    playerId: string;
    /**
     * FlopCard
     */
    cards: Array<{
        type: string;
    } | {
        type: string;
        add: number;
    } | {
        type: string;
        value: number;
    } | {
        type: string;
        multiplier: number;
    } | {
        type: string;
    }>;
    flopThreeCounter: number;
    score: number;
    state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
};

/**
 * RoundSnapshot
 */
export type RoundSnapshot = {
    state: 'started' | 'finished';
    players: Array<{
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    }>;
    currentPlayerId: string;
};

/**
 * GamePlayer
 */
export type GamePlayer = {
    id: string;
    name: string;
};

/**
 * PlayerChoiceRequest
 */
export type PlayerChoiceRequest = {
    id: string;
    type: string;
    /**
     * GamePlayer
     */
    targetPlayer: {
        id: string;
        name: string;
    };
    reason: 'startTurnHitOrStay' | 'firstTurnHit' | 'flopThreeHit';
    choices: Array<string>;
};

/**
 * PlayerSelectionRequest
 */
export type PlayerSelectionRequest = {
    id: string;
    type: string;
    /**
     * GamePlayer
     */
    targetPlayer: {
        id: string;
        name: string;
    };
    reason: 'flopThree' | 'freeze';
    players: Array<{
        id: string;
        name: string;
    }>;
};

/**
 * PlayerRequest
 */
export type PlayerRequest = {
    id: string;
    type: string;
    /**
     * GamePlayer
     */
    targetPlayer: {
        id: string;
        name: string;
    };
    reason: 'startTurnHitOrStay' | 'firstTurnHit' | 'flopThreeHit';
    choices: Array<string>;
} | {
    id: string;
    type: string;
    /**
     * GamePlayer
     */
    targetPlayer: {
        id: string;
        name: string;
    };
    reason: 'flopThree' | 'freeze';
    players: Array<{
        id: string;
        name: string;
    }>;
};

/**
 * GameSummary
 */
export type GameSummary = {
    players: Array<{
        playerId: string;
        totalScore: number;
    }>;
};

/**
 * GameSnapshot
 */
export type GameSnapshot = {
    players: Array<{
        id: string;
        name: string;
    }>;
    /**
     * PlayerRequest
     */
    unfulfilledRequests: Array<{
        id: string;
        type: string;
        /**
         * GamePlayer
         */
        targetPlayer: {
            id: string;
            name: string;
        };
        reason: 'startTurnHitOrStay' | 'firstTurnHit' | 'flopThreeHit';
        choices: Array<string>;
    } | {
        id: string;
        type: string;
        /**
         * GamePlayer
         */
        targetPlayer: {
            id: string;
            name: string;
        };
        reason: 'flopThree' | 'freeze';
        players: Array<{
            id: string;
            name: string;
        }>;
    }>;
    rounds: Array<{
        state: 'started' | 'finished';
        players: Array<{
            playerId: string;
            /**
             * FlopCard
             */
            cards: Array<{
                type: string;
            } | {
                type: string;
                add: number;
            } | {
                type: string;
                value: number;
            } | {
                type: string;
                multiplier: number;
            } | {
                type: string;
            }>;
            flopThreeCounter: number;
            score: number;
            state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
        }>;
        currentPlayerId: string;
    }>;
    /**
     * GameSummary
     */
    summary: {
        players: Array<{
            playerId: string;
            totalScore: number;
        }>;
    };
};

/**
 * GameEvent
 */
export type GameEvent = {
    type: string;
    /**
     * RoundPlayerSnapshot
     */
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    };
} | {
    type: string;
    /**
     * RoundPlayerSnapshot
     */
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    };
} | {
    type: string;
    /**
     * RoundPlayerSnapshot
     */
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    };
} | {
    type: string;
    /**
     * RoundPlayerSnapshot
     */
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    };
} | {
    type: string;
    /**
     * RoundPlayerSnapshot
     */
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    };
} | {
    type: string;
    /**
     * RoundPlayerSnapshot
     */
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    };
} | {
    type: string;
    /**
     * RoundPlayerSnapshot
     */
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
    };
} | {
    type: string;
    payload: {
        playerId: string;
        /**
         * FlopCard
         */
        cards: Array<{
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        }>;
        flopThreeCounter: number;
        score: number;
        state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
        /**
         * FlopCard
         */
        card: {
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        };
    };
} | {
    type: string;
    /**
     * RoundSnapshot
     */
    payload: {
        state: 'started' | 'finished';
        players: Array<{
            playerId: string;
            /**
             * FlopCard
             */
            cards: Array<{
                type: string;
            } | {
                type: string;
                add: number;
            } | {
                type: string;
                value: number;
            } | {
                type: string;
                multiplier: number;
            } | {
                type: string;
            }>;
            flopThreeCounter: number;
            score: number;
            state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
        }>;
        currentPlayerId: string;
    };
} | {
    type: string;
    /**
     * RoundSnapshot
     */
    payload: {
        state: 'started' | 'finished';
        players: Array<{
            playerId: string;
            /**
             * FlopCard
             */
            cards: Array<{
                type: string;
            } | {
                type: string;
                add: number;
            } | {
                type: string;
                value: number;
            } | {
                type: string;
                multiplier: number;
            } | {
                type: string;
            }>;
            flopThreeCounter: number;
            score: number;
            state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
        }>;
        currentPlayerId: string;
    };
} | {
    type: string;
    payload: {
        remainingCards: number;
        totalCards: number;
        /**
         * FlopCard
         */
        card: {
            type: string;
        } | {
            type: string;
            add: number;
        } | {
            type: string;
            value: number;
        } | {
            type: string;
            multiplier: number;
        } | {
            type: string;
        };
    };
} | {
    type: string;
    /**
     * PlayerChoiceRequest
     */
    payload: {
        id: string;
        type: string;
        /**
         * GamePlayer
         */
        targetPlayer: {
            id: string;
            name: string;
        };
        reason: 'startTurnHitOrStay' | 'firstTurnHit' | 'flopThreeHit';
        choices: Array<string>;
    };
} | {
    type: string;
    /**
     * PlayerSelectionRequest
     */
    payload: {
        id: string;
        type: string;
        /**
         * GamePlayer
         */
        targetPlayer: {
            id: string;
            name: string;
        };
        reason: 'flopThree' | 'freeze';
        players: Array<{
            id: string;
            name: string;
        }>;
    };
} | {
    type: string;
    /**
     * GameSnapshot
     */
    payload: {
        players: Array<{
            id: string;
            name: string;
        }>;
        /**
         * PlayerRequest
         */
        unfulfilledRequests: Array<{
            id: string;
            type: string;
            /**
             * GamePlayer
             */
            targetPlayer: {
                id: string;
                name: string;
            };
            reason: 'startTurnHitOrStay' | 'firstTurnHit' | 'flopThreeHit';
            choices: Array<string>;
        } | {
            id: string;
            type: string;
            /**
             * GamePlayer
             */
            targetPlayer: {
                id: string;
                name: string;
            };
            reason: 'flopThree' | 'freeze';
            players: Array<{
                id: string;
                name: string;
            }>;
        }>;
        rounds: Array<{
            state: 'started' | 'finished';
            players: Array<{
                playerId: string;
                /**
                 * FlopCard
                 */
                cards: Array<{
                    type: string;
                } | {
                    type: string;
                    add: number;
                } | {
                    type: string;
                    value: number;
                } | {
                    type: string;
                    multiplier: number;
                } | {
                    type: string;
                }>;
                flopThreeCounter: number;
                score: number;
                state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
            }>;
            currentPlayerId: string;
        }>;
        /**
         * GameSummary
         */
        summary: {
            players: Array<{
                playerId: string;
                totalScore: number;
            }>;
        };
    };
} | {
    type: string;
    /**
     * GameSnapshot
     */
    payload: {
        players: Array<{
            id: string;
            name: string;
        }>;
        /**
         * PlayerRequest
         */
        unfulfilledRequests: Array<{
            id: string;
            type: string;
            /**
             * GamePlayer
             */
            targetPlayer: {
                id: string;
                name: string;
            };
            reason: 'startTurnHitOrStay' | 'firstTurnHit' | 'flopThreeHit';
            choices: Array<string>;
        } | {
            id: string;
            type: string;
            /**
             * GamePlayer
             */
            targetPlayer: {
                id: string;
                name: string;
            };
            reason: 'flopThree' | 'freeze';
            players: Array<{
                id: string;
                name: string;
            }>;
        }>;
        rounds: Array<{
            state: 'started' | 'finished';
            players: Array<{
                playerId: string;
                /**
                 * FlopCard
                 */
                cards: Array<{
                    type: string;
                } | {
                    type: string;
                    add: number;
                } | {
                    type: string;
                    value: number;
                } | {
                    type: string;
                    multiplier: number;
                } | {
                    type: string;
                }>;
                flopThreeCounter: number;
                score: number;
                state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
            }>;
            currentPlayerId: string;
        }>;
        /**
         * GameSummary
         */
        summary: {
            players: Array<{
                playerId: string;
                totalScore: number;
            }>;
        };
    };
} | {
    type: string;
    /**
     * GameSnapshot
     */
    payload: {
        players: Array<{
            id: string;
            name: string;
        }>;
        /**
         * PlayerRequest
         */
        unfulfilledRequests: Array<{
            id: string;
            type: string;
            /**
             * GamePlayer
             */
            targetPlayer: {
                id: string;
                name: string;
            };
            reason: 'startTurnHitOrStay' | 'firstTurnHit' | 'flopThreeHit';
            choices: Array<string>;
        } | {
            id: string;
            type: string;
            /**
             * GamePlayer
             */
            targetPlayer: {
                id: string;
                name: string;
            };
            reason: 'flopThree' | 'freeze';
            players: Array<{
                id: string;
                name: string;
            }>;
        }>;
        rounds: Array<{
            state: 'started' | 'finished';
            players: Array<{
                playerId: string;
                /**
                 * FlopCard
                 */
                cards: Array<{
                    type: string;
                } | {
                    type: string;
                    add: number;
                } | {
                    type: string;
                    value: number;
                } | {
                    type: string;
                    multiplier: number;
                } | {
                    type: string;
                }>;
                flopThreeCounter: number;
                score: number;
                state: 'active' | 'busted' | 'frozen' | 'stayed' | 'won';
            }>;
            currentPlayerId: string;
        }>;
        /**
         * GameSummary
         */
        summary: {
            players: Array<{
                playerId: string;
                totalScore: number;
            }>;
        };
    };
};

export type GetGameEventsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/game/events';
};

export type PostGameRequestsData = {
    body: {
        requestId: string;
        playerId: string;
        choice: string;
    };
    path?: never;
    query?: never;
    url: '/game/requests';
};
